/** SCRIVERE UN SEMPLICE PROGRAMMA CHE SVOLGA LE SEGUENTI OPERAZIONI ARITMETICHE CORRETTAMENTE, SCEGLIENDO ACCURATAMENTE I TIPI  DI DATI DA UTILIZZARE PER IMMAGAZZINARE
    I RISULTATI I ESSE. UNA DIVISIONE  TRA DUE INTERI A = 5 E B = 3. IMMAGAZZINARE IL RISULTATO IN UNA VARIABILE R1, SCEGLIENDO IL TIPO DI DATO ADEGUATO.
    UNA MOLTIPLICAZIONE TRA UN CHAR C='A' ED UNO SHORT S = 5000. IMMAGAZZINARE IL RISULTATO IN UNA VARIABILE R2 DI TIPO ADEGUATO.
    UNA SOMMA TRA UN INT I=6 ED UN FLOAT F=3.14F. IMMAGAZZINARE IL RISULTATO IN UNA VARIABILE R3 DI TIPO ADEGUATO.
    UNA SOTTRAZIONE TRA R1,R2 E R3. IMMAGAZZINARE IL RISULTATO IN UNA VARIABILE R4, SCEGLIENDO IL TIPO DI DATO ADEGUATO.
*/

public class Esercizio3A {
public static void main(String argv[]){
	int a = 5, b = 3;
double r1 = (double)a/b;
System.out.println("r1 = " + r1);

char c = 'a';
short s = 5000;

int r2 = c*s;
System.out.println("r2 = " + r2);

int i = 6;
float f = 3.14F;
float r3 = i + f;
System.out.println("r3 = " + r3);

double r4 = r1 - r2 - r3;
System.out.println("r4 = " + r4);

}

} 
