/** IN QUESTA SEZIONE SI UTILIZZA IL CONCETTO DI CLASSE ASTRATTA PER DEFINIRE ELEMENTI COMUNI AD UN INSIEME DI OGGETTI REALIZZATI NELLE SOTTOCLASSI DEFINENTI TALI OGGETTI
*   E L'USO DELLA FUNZIONALITA' PACKAGE. IN PARTICOLARE SI PRENDE COME RIFERIMENTO LE FIGURE GEOMETRICHE CARATTERIZZATE DA AREA E PERIMETRO. LE RAPPRESENTAZIONI DI QUESTI
*   SONO COMUNI A TUTTE LE FIGURE MA LE PROCEDURE SONO PROPRIE DI CIASCUN TIPO DI FIGURA. QUINDI SI USA UNA CLASSE ASTRATTA, CHE NON PUO' ESSERE ISTANZIATA, PER DEFINIRE 
*   LE VARIABILI AREA E PERIMETRO E PER INDICARE I METODI CHE LE SOTTOCLASSI DEVONO REALIZZARE 										*/
